version: '3.1'

services:
  sql-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: some
    ports:
      - "5432:5432"

  key-db:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  no-sql:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: master
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: some 

