apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test
  name: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
    spec:
      containers:
      - image: test:latest
        name: test
        imagePullPolicy: Never
        ports:
          - name: web-server
            containerPort: 5000
        resources: {}
        livenessProbe: 
          httpGet: 
            path: /status
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5

        readinessProbe: 
          httpGet: 
            path: /status
            port: 5000
            httpHeaders: 
            - name: Custom-Status 
              value: "running"   
          initialDelaySeconds: 3  
          periodSeconds: 3

status: {}
