definitions:
  steps:
    - step: &build-test
        name: Build and go fu
        script:
          - mvn package
        artifacts:
          - target/**

pipelines:
  branches:
    develop:
      - step: *build-test
    main:
      - step: *build-test
